5th task
js-tasks-ru/js-20201211_e-watson pull request #4
Opened 2021-01-14 07:07 UTC by e-watson

2021-01-14 07:13 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-15 15:35 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage.notification = this.element;
Подскажите пожалуйста что происходит в строке 8. 
Для чего нам необходимо данное присваивание: `NotificationMessage.notification = this.element;` ?

2021-01-15 15:36 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      return;
в данном случае этот `return` оборвет выполнение метода `sort`. Такая и была задумка?

2021-01-15 15:37 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let headerCell = this.element.querySelector(`[data-id=${columnDescription.id}]`);
`headerCell` - это `const`. Помните почему?

2021-01-15 15:37 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2021-01-19 08:26 UTC, e-watson commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage.notification = this.element;
notification - статическое поле для типа. Оно одно для всех экземпляров типа и, в данном случае, работа с ним обеспечивает доступ к единственному контенту окна сообщения, его пересозданию/удалению.

да, для полного совпадения с тем, что было показано на лекции, надо перед строкой 5 добавить такой код:
    if (NotificationMessage.notification) {
      NotificationMessage.notification.remove();
    }

но тест проходит, что, честно говоря, меня немного нервирует в этом курсе :-(

2021-01-19 08:29 UTC, e-watson commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      return;
Правильная задумка - обдуманно пользоваться линтером. Но в данном случае: да, если сортировки нет - зачем, что-либо делать дальше?

2021-01-19 08:32 UTC, e-watson commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let headerCell = this.element.querySelector(`[data-id=${columnDescription.id}]`);
Да, лучше const. Это постоянный указатель на область памяти и последующая защита от перезаписывания. Хотя, его поля и модифицируемые. Довольно странная штука для тех, кто работает с C#, например

2021-01-19 16:37 UTC, dosandk commented
@e-watson Пожалуйста поправьте `Notification` компонент. Согласно условию задачи каждый последующий вызов должен скрывать предыдущий нотификейшен. Именно для это и нужно добавить строки:
```
if (NotificationMessage.notification) {
NotificationMessage.notification.remove();
}
```

2021-01-20 06:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-21 14:10 UTC, dosandk approved these changes

2021-01-21 14:11 UTC, merged